### ISSUE TITLE
Деталі працівника: зменшити відстань між заголовками табів (міжрядковий інтервал)

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#111]
За взірець взяти відстань між табами на сторінці Склад http://ss.div.agency/store.html
![2](https://user-images.githubusercontent.com/32901362/35524254-b7e71e52-0529-11e8-812a-9527ffa4aeb0.png)
![1](https://user-images.githubusercontent.com/32901362/35524255-b80651be-0529-11e8-8c47-9e5176b7c42a.png)

**Comment by HalynaNasteka** [comment]
коли у другому рядку тільки 1 таб (Штрафи і премії), то міжрядкова вдстань ще завелика
![image](https://user-images.githubusercontent.com/32901362/35575470-19303200-05e5-11e8-93f2-3aac282826cb.png)

**Comment by divppc** [comment]
насправді тут трохи проблемка бо універсального рішення немає - не завжди відомо в який момент таби встануть в один ряд, щоб задати їм інші відступи в цей момент. Зараз більший відступ задається для екранів >= 1600, прошу переглянути
