### ISSUE TITLE
Стиль кнопок на попапах - наблизити до стилю кнопок на скрінах.

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#13]
![11](https://user-images.githubusercontent.com/32901362/31960537-c52c63f8-b900-11e7-82d4-019c159c903c.png)
Кнопкам дати такий стиль:
![11](https://user-images.githubusercontent.com/32901362/31960578-e81b6ecc-b900-11e7-9daf-dcd4e1183c55.png)
А червоній іконці колір червоний #e74c3c
Намагаємося користуватися тими кольорами, що присутні вже у дизайні

**Comment by HalynaNasteka** [comment]
стиль бачу змінено, колір червоної іконки теж, але колір синьої кнопки ще синій яскравий, такого на сайті ніде нема більше. треба поставити колір #569cb5

**Comment by divppc** [comment]
готово
