### ISSUE TITLE
Orders (ширина 768б 800, 900) - елементи у фільтрі нерівномірно розподілені

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#2]
![11](https://user-images.githubusercontent.com/32901362/31718306-173c105a-b418-11e7-992f-1b6ef98d703f.png)

**Comment by divppc** [comment]
Маєте на увазі поділити список порівну на дві частини?

**Comment by HalynaNasteka** [comment]
Порівну не вийде, бо не парна кількість. Але щоб у першій було не більше ніж на 1 елемент більше
