### ISSUE TITLE
Print - список закривається після кліку на 1 чекбокс

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#22]
Що є не логічно, оскільки це мультиселект і список має залишатися відкритим, поки користувач вибере всі елементи, що йому необхідні
![11](https://user-images.githubusercontent.com/32901362/32053278-82ea5ebe-ba63-11e7-94d9-1dc0c5acc2e6.png)

**Comment by divppc** [comment]
ага, то машинальна помилка) виправлено
