### ISSUE TITLE
На попапах кнопки зробити в стилі, як Save і Cancel на формі Order Details

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#26]
Сіра кнопка закрити виглядає дуже похмуро. Тому для послідовності, варто застосувати такі кольори, які є в кнопках Save і Cancel на формі Order Details
![1](https://user-images.githubusercontent.com/32901362/32062235-9196f0f8-ba7c-11e7-957d-fa5405303715.png)
![2](https://user-images.githubusercontent.com/32901362/32062225-8e862a78-ba7c-11e7-9457-e3619e3aec93.png)

**Comment by divppc** [comment]
готово
