### ISSUE TITLE
Cashboxes: заголовок таблиці має бути Cashbox 1 Name Transaction History

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#34]
![1](https://user-images.githubusercontent.com/32901362/32392289-ae60308e-c0dd-11e7-8f20-0c566030ba3a.png)
Змінити заголовок таблиці з CashDesk на Cashbox 1 Name Transaction History

**Comment by HalynaNasteka** [comment]
Цецй заголовок у верху сторінки, відповідно, забираємо, раз ми перенесли його в заголовок таблиці.
![1](https://user-images.githubusercontent.com/32901362/32415220-ba499fe0-c23e-11e7-91f7-b74a754f378d.png)

**Comment by divppc** [comment]
забрав
