### ISSUE TITLE
Order Details - Personnel In charge має бути назвою розділу (як наприклад Additional information)

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#5]
і в цьому блоці вже 4 випадних списка
Accepted by 
Assigned to 
Manager 
Repairman 
![11](https://user-images.githubusercontent.com/32901362/31719732-145606d4-b41d-11e7-83eb-fd1729460c9a.png)

**Comment by divppc** [comment]
аа, зрозумів
