### ISSUE TITLE
Стрілочка від дзвіночка трішки змінює свою позицію після натискання

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#54]
коли клікнути на дзвіночок, стрілка з'являється в одній позиції, через секунду трішки "стрибає вправо". Крім того, стрілка завжди темно-синя, а при наведенні на іконку дзвіночка колір іконки змінюється на світліший. Мождиво доцільніше буде повенрнутися до варіанту, коли стрілочка з нотифікації.

**Comment by HalynaNasteka** [comment]
Щоб було по аналогії з меню профіля, там теж стрілочка зі списку до іконки. і ефект такий самий дати списку нотифікацій, щоб була послідовність і поменше різних ефектів.

**Comment by divppc** [comment]
знову не відтворюється проблема, не стрибиає стрілка) фон при наведені на дзвіночок можу змінити. Пропоную виправити ефекти стрибання стрілки (спочатку треба його побачити) і залишит таку, тому що тут присутній скрол коли нотифікацій буде багато. Зараз при скролі все гарно веде себе, коли сторінка проскролена нижче хедера - нотифікації тянуться вверху. Якщо зробити таку ж стрілку як у меню користувача - то при першому ж скролі колесом вона стане невидимою.
