### ISSUE TITLE
Order Details: якщо в історії лінк, не завжди влазить у відведений контейнер

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#63]
![1](https://user-images.githubusercontent.com/32901362/33214068-04c8e79e-d133-11e7-9399-a0532912635c.png)

**Comment by divppc** [comment]
done http://ss.div.agency/order-details.html

**Comment by HalynaNasteka** [comment]
час відсутній біля лінка
![1](https://user-images.githubusercontent.com/32901362/33215418-55c37538-d138-11e7-9812-9eb4c9faa68e.png)

**Comment by divppc** [comment]
його там фізично немає, напевно в макеті не було, все буде ок якщо поставити http://joxi.ru/BA0ogv0IBRyNq2
