### ISSUE TITLE
Нотифікації перекриваються іншими випадаючими елементами (add comment, Print, order status)

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#65]
![3](https://user-images.githubusercontent.com/32901362/33271687-a30b46b8-d390-11e7-9f6c-3385875f4d7c.png)
![2](https://user-images.githubusercontent.com/32901362/33271688-a331534e-d390-11e7-89bf-ca259d1439aa.png)
![1](https://user-images.githubusercontent.com/32901362/33271690-a3504b3c-d390-11e7-9fd3-98249a542b28.png)

**Comment by divppc** [comment]
нотифікації повинні перекривати все інше коли вони відкриті?

**Comment by HalynaNasteka** [comment]
не усе, меню профіля ми домовилися, що буде зверху (маню зверху нотифіцікацій). А решта елементів - нотифікації зверху
