### ISSUE TITLE
Якщо таблицю поскролити горизонтально і клікнути, ефект засвітлення не на всю таблицю, обрізаний

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#67]
![1](https://user-images.githubusercontent.com/32901362/33515597-31c75852-d76e-11e7-8dad-c25132dba61b.png)

**Comment by divppc** [comment]
зробив затемнення на всю ширину, але сам прелоадер повинен залишитись там, не можна вставити в таблицю просто блок, не ячейку
