### ISSUE TITLE
Журнал - стиль полів другого рядка фільтра відрізняється від решти

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#69]
![1](https://user-images.githubusercontent.com/32901362/33515930-46768d46-d772-11e7-9598-6dd9676e5224.png)

**Comment by divppc** [comment]
зробити всі білим чи всі сірим?

**Comment by divppc** [comment]
зробив сіруватими

**Comment by HalynaNasteka** [comment]
зробити всі, як на решті форм з фільтрами. якщо не помиляюся, то білі усюди
