### ISSUE TITLE
Order Details - список з вибором статусу - заокруглити кутики і фон змвнити синій на білий

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#7]
![11](https://user-images.githubusercontent.com/32901362/31723417-736b2596-b427-11e7-88de-35c4d8e195d1.png)
синій список зливається з формою і не зовсім зрозуміло що там можна робити вибір. Краще зробити фон списка білим.

**Comment by divppc** [comment]
Розумію про що ви, але це звичайний select. Стилі випадаючого меню наслідуються зверху, тобто якщо поставити білий фон, то він просто злиється з білим текстом і получиться білий квадрат замість списку. 

Якщо стоїть потреба стилізувати його, то треба робити обманку, два різні блоки і трохи js і відмовитись від select, варто?

**Comment by HalynaNasteka** [comment]
ні, у цьому випадку не варто. принаймні, не на цьому етапі

**Comment by divppc** [comment]
згоден, як альтернатива можна зробити якось так http://joxi.ru/12MBRjWSMdna1A
тобто темніший фон дати, щоб виділявся

**Comment by HalynaNasteka** [comment]
можна спробувати так, як Ви пропонуєте - темніший. якщо не буде ні від кого зауважень, залишимо)

**Comment by divppc** [comment]
затемнив
