### ISSUE TITLE
На усіх вкладках складу для таблиць має бути такий самий пейджинг, як усюди на сайті (Show more)

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#73]
![2](https://user-images.githubusercontent.com/32901362/33516460-cb8e2c60-d77b-11e7-8307-9022c36b6020.png)
![1](https://user-images.githubusercontent.com/32901362/33516458-c8a94048-d77b-11e7-9114-da7047e2b12c.png)

**Comment by divppc** [comment]
тобто замість існуючого?

**Comment by HalynaNasteka** [comment]
так, замість існуючого. щоб була послідовність у інтерфейсі
