### ISSUE TITLE
Оприходования/Смотреть по оприходованным позициям - у фільтрі відсутнє друге поле для дати

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#76]
Є тільки дата "Від" , а дати "до" нема
![1](https://user-images.githubusercontent.com/32901362/33516664-344182f4-d77f-11e7-81a9-f1d929c59250.png)

**Comment by divppc** [comment]
якщо не помиляюсь так було в тз, але виправив на всякий
