### ISSUE TITLE
Новое  оприходование: стилі списку введених номерів змінити, щоб відрізнядися від звичайних лейблів

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#79]
Можна їм дати колір сірий, як тексти інструкцій,
також помістити їх під полем (вирівняти по лівому краю поля)
і додати іконку для видалення (хрестик)
![1](https://user-images.githubusercontent.com/32901362/33517170-f3e8c876-d787-11e7-83b4-720e34797d6b.png)

**Comment by divppc** [comment]
цей пункт не готовий, список просто вставлений, буде реалізовано пізніше з можливістю редагування, згідно ТЗ

**Comment by divppc** [comment]
зроблена реалізація і добавлені стилі. Сподіваюсь правильно зозумів по тз як ці поля повинні працювати
