### ISSUE TITLE
Оприходования/Смотреть по оприходованным позициям - клік на номер оприходування у таблиці затемняє скрін

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#80]
Ідентична ситуація на скріні Списания/Смотреть по списанным позициям
![1](https://user-images.githubusercontent.com/32901362/33517755-535973dc-d792-11e7-9db7-e07d14049d1b.png)

**Comment by HalynaNasteka** [comment]
Ідентична ситуація на скріні Перемещения/Смотреть по перемещенным позициям

**Comment by divppc** [comment]
у цих двох випадках модальне вікно розміщено прямо під номером, в таблиці, так як Юра завжди просить. Я б міг зробити глобальне модальне вікно для наглядності, а наступною правкою він попросить занести прямо в таблицю, тому це для економії часу, він зрозуміє.
