### ISSUE TITLE
Новое списание-додати ікони видалення для записів у таблиці "Товары к списанию"

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#81]
![1](https://user-images.githubusercontent.com/32901362/33517810-4ae8717a-d793-11e7-8378-78984bfe92c1.png)

**Comment by HalynaNasteka** [comment]
а ці цконки йдуть тільки парою (редагування+видалення)? бо у цьому випадку потрібні тільки іконки видалення

**Comment by divppc** [comment]
ні, не обоявязково парою, зміню

**Comment by divppc** [comment]
done
