### ISSUE TITLE
Work And Supplies - кнопку Select from Warehouse помістити поряд з кнопкою Add part

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#9]
Знаю, на мокапі теж таке не раціональне розташування, Ви зробили згідно з мокапом. Але ми працюємо разом на хороший результат)
![11](https://user-images.githubusercontent.com/32901362/31957863-b2f8bf54-b8f8-11e7-9d1e-25ab37144171.png)
![11](https://user-images.githubusercontent.com/32901362/31957895-cf51144e-b8f8-11e7-9e9d-f5bde39bd1d5.png)

**Comment by HalynaNasteka** [comment]
Усе-таки треба поміняти мвсцями кнопки Select form Warehouse і Add part, щоб була послідовність у розміщенні кновки додаванні елементу (кнопка Add work справа, і Add work хай буде справа)
![11](https://user-images.githubusercontent.com/32901362/32049843-424511d0-ba57-11e7-9b11-8ab580b70f8a.png)

**Comment by divppc** [comment]
> кнопка Add work справа, і Add work хай буде справа))

поміняв місцями, думаю правильно зрозумів.
