### ISSUE TITLE
Детали возврата: на формы мають бути кнопки Закрыть і Удалить

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#90]
кнопка Создать не потрібна
треба додати кнопку чи іконку видалення, як усюди на деталях сутності
![1](https://user-images.githubusercontent.com/32901362/34070381-f5aa8e1a-e26d-11e7-9238-8f866fc1df04.png)

**Comment by divppc** [comment]
змінив кнопку, але тепер вона відповідно не закриває модалку, по кліку має бути інший хендлер

**Comment by HalynaNasteka** [comment]
кнопка Закрити має бути, і крім неї ще іконка видалення. Так і написала ж у задачі)
