### ISSUE TITLE
Деталі клієнта: на першій вкладці відсутні кнопки

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#93]
потрібно додати кнопки СОхрагить, Закрыть, Удалить
![1](https://user-images.githubusercontent.com/32901362/34070891-cfc4eeae-e275-11e7-8fa9-05d62398152d.png)
![2](https://user-images.githubusercontent.com/32901362/34070893-d37e1eee-e275-11e7-97a8-aee9c610e114.png)

**Comment by divppc** [comment]
тут кнопки не ставив, тому що вирішили робити цей розділ окремою сторінкою, а не модалкою. Вважаєш потрібні?

**Comment by HalynaNasteka** [comment]
Зберегти і видалення точно потрібні. якщо окрема сторінка, то можна обійтися без кнопки Закрити.
Інакше нема як зберегти зміни в формі
