### ISSUE TITLE
Деталі клієнта/вкладака Платежі: позитивні суми мають бути зелені, негативні червоні

### ISSUE THREAD

**Issue by HalynaNasteka** [divppc/SmartService#94]
![2](https://user-images.githubusercontent.com/32901362/34070919-614ff2f6-e276-11e7-87f3-7b814f9ac3e3.png)
![1](https://user-images.githubusercontent.com/32901362/34070920-616d66c4-e276-11e7-99ed-790a7c66355d.png)

**Comment by divppc** [comment]
done

**Comment by HalynaNasteka** [comment]
на вкладні Платежі так має бути. ти зробив на вкладні Продажі)

**Comment by divppc** [comment]
ой, сорі, спішка

**Comment by divppc** [comment]
переніс
